### ISSUE TITLE
Cron job does not run correctly?

### ISSUE THREAD

**Issue by hotbirdx** [moafrancky/speedtest2mqtt#10]
I liked your idea to post the speedtest results to mqtt. I tested the docker but it doesn't give the correct result. My CRON variable is: 30 * * * *.  
The script: entrypoint.sh seems to run because it creates a cron job. Starting the script: speedtest2mqtt.sh manually also works and gives mqtt results. The logfile: /var/tmp/cron.log is empty and the logfile: /var/tmp/crond.log has the content in the attached file.

![Screenshot 2021-05-25 183147](https://user-images.githubusercontent.com/71672064/119534768-92704d00-bd87-11eb-86e6-0d875a3748e0.jpg)

Perhaps because in Alpine the crond has to be started as root? [https://stackoverflow.com/questions/63046301/how-to-run-cron-as-non-root-in-alpine](url)

**Comment by moafrancky** [comment]
Hi,

I've tested this docker with CRON 30 * * * * and it works pretty well. I use moafrancky/speedtest2mqtt:latest and a docker-compose.yml file. What is your context ?

Kind regards.

**Comment by hotbirdx** [comment]
Hi,

Thank you for responding. I am running your docker (latest) image on a
Synolgy DS412+ NAS. The Linux version of the NAS is: Linux version 3.10.105
***@***.***) (gcc version 4.9.3 20150311). The Docker version is:
18.09.0-0519. I added the image with the following config and environment
variables:
[image: image.png]

[image: image.png]

[image: image.png]

The environment variables are transferred to the file:
/var/tmp/container.env   :

[image: image.png]

Because the config is added in the Docker GUI, I do not (cannot?) use a
docker-compose.yml file.
Hope this information helps. Please let me know if you need extra info.

Kind regards,

Olaf.

**Comment by moafrancky** [comment]
Hi,

I used comments found here [https://github.com/gliderlabs/docker-alpine/issues/381](url) to have cron running as non root user. 

I guess that `setcap cap_setgid` may require high privileges on your platform. I will follow latest comment found in issue 381, replace crond by yacron and see if it runs fine.

Kind regards.

**Comment by moafrancky** [comment]
Hi,

I've now switched to yacron. I guess that it should be ok now.

Thanks

**Comment by hotbirdx** [comment]
Hi,

I just tested the new image with yacron and it works perfect now!
Thanks for your effort.
